// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Assignment4Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    // Test 1: Valid data - Age = 24, Driving Experience = 3, Accidents = 0

    [Test]
    public void InsuranceQuote01_ValidData()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(786, 802);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("24");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("age")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("24"));
        }
    }

    // Test 2: Valid data but Accidents = 4 (too many accidents)

    [Test]
    public void InsuranceQuote02_TooManyAccidents()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(790, 804);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("4");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("accidents")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("4"));
        }
    }

    // Test 3: Valid data - Age = 35, Driving Experience = 9, Accidents = 2

    [Test]
    public void InsuranceQuote03_ValidOlderDriver()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(794, 804);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("9");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("age")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("35"));
        }
    }

    // Test 4: Invalid phone number

    [Test]
    public void InsuranceQuote04_InvalidPhoneNumber()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(786, 802);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }

    // Test 5: Invalid email address

    [Test]
    public void InsuranceQuote05_InvalidEmail()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(794, 804);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-599-9978");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("keronbalar");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
    }

    // Test 6: Invalid postal code

    [Test]
    public void InsuranceQuote06_InvalidPostalCode()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(798, 804);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Parkside Drive, Waterloo");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L4X7");
        driver.FindElement(By.Id("phone")).SendKeys("4375669397");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9397");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("15");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
    }

    // Test 7: Missing age

    [Test]
    public void InsuranceQuote07_MissingAge()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(786, 802);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
    }

    // Test 8: Missing number of accidents

    [Test]
    public void InsuranceQuote08_MissingAccidents()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(790, 804);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("37");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("8");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
    }

    // Test 9: Missing years of driving experienc

    [Test]
    public void InsuranceQuote09_MissingExperience()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(786, 802);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
    }

    // Test 10: Age < 16 (invalid)

    [Test]
    public void InsuranceQuote10_AgeBelowMinimum()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(786, 802);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("15");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("0");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Please enter a value greater than or equal to 16."));
    }

    // Test 11: Experience exceeds age limit

    [Test]
    public void InsuranceQuote11_ExperienceExceedsAge()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(786, 802);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("30");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("20");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("experience")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("20"));
        }
    }

    // Test 12: Accidents = 0, Valid older driver, with reduction

    [Test]
    public void InsuranceQuote12_OlderDriverReduction()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(786, 802);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("40");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("age")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("40"));
        }
    }

    // Test 13: Experience exceeds age limit

    [Test]
    public void InsuranceQuote13_ExperienceExceedsAge()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(786, 802);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("50");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("40");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("experience")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("40"));
        }
    }

    // Test 14: Valid data with 1 accident

    [Test]
    public void InsuranceQuote14_OneAccident()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(786, 802);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("7");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("accidents")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("1"));
        }
    }

    // Test 15: Valid data with no reduction

    [Test]
    public void InsuranceQuote15_ValidNoReduction()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(786, 802);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Keron");
        driver.FindElement(By.Id("lastName")).SendKeys("Balar");
        driver.FindElement(By.Id("address")).SendKeys("533 Glen Forrest Blvd");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2L 4H9");
        driver.FindElement(By.Id("phone")).SendKeys("4375669398");
        driver.FindElement(By.Id("email")).SendKeys("balarkeron11@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-566-9398");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("29");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("1");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("accidents")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("0"));
        }
    }
}

